[package]
name = "discord-tauri"
version = "0.2.0"
description = "A Discord wrapper using Tauri"
authors = [ "DrPuc" ]
license = ""
repository = ""
default-run = "discord-tauri"
edition = "2018"
build = "src/build.rs"

[build-dependencies]
tauri-build = { version = "1.0.0-beta.3" }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
tauri = { version = "1.0.0-beta.5", features = ["api-all", "menu", "system-tray"] }

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]

[patch.crates-io]
wry = { git = "https://github.com/tauri-apps/wry", branch = "fix/cursor-flicker" }
